version = 0.1

[default.deploy]
stack_name = "calculator-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r8awnvexkdwn"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = true
